### ISSUE TITLE
legacy images need to align right

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#793] opened 2018-10-01 23:50 UTC
Legacy images on these pages won't align right, even with `-right` added to `legacy-img`
(reference: [Peace Corps image on post](https://digital.gov/2018/01/30/making-customer-satisfaction-data-actionable-at-peace-corps/))

- [x] Three images on https://digital.gov/2016/07/28/widgets-mobile-apps-and-sms-essential-agency-tools-for-summer-heat-safety-and-hurricane-season/
- [x] One image at "Analytics.USA.gov" on https://digital.gov/2015/09/28/nasa-lunar-eclipse-a-supermoon-match-made-in-metrics-heaven/
- [x] One image on https://digital.gov/2012/10/01/automated-translation-good-solution-or-not/

## it's done when …
- [x] all 5 are aligned right

**Comment by ToniBonittoGSA** [comment] 2018-11-27 19:59
@jeremyzilar added a new one

**Comment by monkeywithacupcake** [comment] 2019-09-23 13:35
One solution is to `float: right` the containing `<a>` and `clear:right` the following `<p>`

**Comment by monkeywithacupcake** [comment] 2019-10-02 12:29
Question: If the fix was merged and the issue is in the Done/Merged board, should the issue be closed? Is this still an issue?
When I look at the links, the images are still on the left.

**Comment by jeremyzilar** [comment] 2019-10-02 16:47
@monkeywithacupcake This fix made the shortcode that we use for aligning the issues on the right work properly, though that doesn't mean that the all the posts are using that shortcode.

**Next steps are to:**

- [ ] document the shortcodes in our [Wiki](https://github.com/GSA/digitalgov.gov/wiki/Hugo-shortcodes)
- [ ] go through the posts that have images that need to align right and apply the correct shortcode

**Comment by jeremyzilar** [comment] 2020-01-30 13:53
This has been completed 🎉👾

**Closed by jeremyzilar** 2020-01-30 13:53 UTC
Labels: Bug, Bug: Content Cleanup, Content: Images
