### ISSUE TITLE
Pulse.cio.gov should be removed from this page

### ISSUE THREAD

**Issue by tdlowden** [GSA/digitalgov.gov#2996] opened 2020-07-15 20:21 UTC
**Tools and Services**
https://digital.gov//services/

---

**Please describe the issue clearly. Include a screenshot if needed**

Pulse.cio.gov has been retired.

**Comment by saracope** [comment] 2020-07-21 18:13
closing as duplicate of #2749

**Closed by saracope** 2020-07-21 18:13 UTC
