### ISSUE TITLE
Remove Pulse references

### ISSUE THREAD

**Issue by gbinal** [GSA/digitalgov.gov#2815] opened 2020-06-25 18:43 UTC
### URL / Link to page

https://digital.gov/services/directory/
https://digital.gov/services/

### Tell us how we can make this page better

The Pulse website was deprecated by OGP and no longer exists.  I'd suggest removing the links to it on those pages.

**Comment by afeijoo** [comment] 2020-06-26 12:05
Replace `Pulse` references with `Digital Dashboard`.

title: Digital Dashboard
summary: Reports on agencies and websites to help federal agencies do digital better
source_url: https://digitaldashboard.gov/
logo: See https://digitaldashboard.gov/sites/all/themes/dotgov/images/DD_Logo-new.png
contact: dotgovdashboard@gsa.gov
authors: https://digital.gov/authors/marina-fox/

@smarina04 Please review and update the DD metadata if needed.

**Comment by saracope** [comment] 2020-07-21 18:13
closing as duplicate of #2749

**Closed by saracope** 2020-07-21 18:13 UTC
Labels: feedback
