### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by DanielJPino-ux** [GSA/digitalgov.gov#1700] opened 2019-12-16 14:02 UTC
### URL / Link to page
https://digital.gov/event/2019/12/19/uswds-december-monthly-call/

"Add to calendar" button is not working

**Comment by jeremyzilar** [comment] 2019-12-16 16:01
This is a duplicate of https://github.com/GSA/digitalgov.gov/issues/1651 and will get fixed soon

**Closed by jeremyzilar** 2019-12-16 16:01 UTC
Labels: feedback
